name: multigauge
description: "Provides a multi-band gauge."
version: 1.0.0
homepage: https://github.com/greensopinion/multigauge

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
